### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by siku2** [ryan-lang/homeassistant-davis-local#1]
This would've been better suited as a discussion, but since they aren't enabled on this repository (at the time of writing) I'm creating this issue instead.

I just randomly stumbled upon your repository and was wondering whether you're aware of the project I started back in 2021, which is doing the same thing as yours: https://github.com/siku2/hass-weatherlink

The integration has aged a bit as there have been a lot of changes in Home Assistant and I'm planning on doing a major overhaul in the coming days, so I'm here because I want to see what we can learn from each other.

One thing you might be interested in is the [WeatherLink Broadcast API](https://github.com/siku2/hass-weatherlink/blob/22f68f15dcbf48ad11b3312e0d4560750f66722a/custom_components/weatherlink/api/broadcast.py) implementation, which allows the Home Assistant instance to passively receive information from the weatherlink / airlink devices with a much higher frequency than would be possible using polling.

I'm excited to see that you've started to implement AQI calculation. That's something that I've wanted to add back then, but never got to. Can you tell me where you're getting the parameters for the calculation from?

**Comment by siku2** [comment]
Oh and another thing that might interest you is that you can [discover weatherlink and airlink devices in the network using zeroconf](https://github.com/siku2/hass-weatherlink/blob/a448fa7e76cde9b4ddf31741828b2e9275b3057b/custom_components/weatherlink/manifest.json#L13-L16).

**Comment by ryan-lang** [comment]
Hi there, thanks for reaching out! As you can maybe tell, my implementation is just a quick & dirty approach to get something working over the weekend. I'm not sure how I missed yours, but seems like it could have saved me some effort! I'd be happy to redirect my future efforts towards your project, so we can converge on a single feature set. 

To that end, I'll answer your question about AQI in the existing discussion on your repo.

Generally, do you have a roadmap for your overhaul? Maybe it'd be most useful for me to wait and see what that looks like before contributing anything?

**Comment by siku2** [comment]
> Generally, do you have a roadmap for your overhaul? Maybe it'd be most useful for me to wait and see what that looks like before contributing anything?

I'm hoping to get it done by the end of the week. Since this will basically be a full rewrite I think you might want to hold back with any major contributions until then. However, if you have more ideas that I should be taking into consideration while working on it, do let me know!
